### ISSUE TITLE
One small question about the Local Contrast Norm

### ISSUE THREAD

**Issue by wuyongfa-genius** [kevtimova/deep-sparse#2]
Thanks for your excellent work. I may have one small question that what is the purpose of using local contrast norm and can it be safely removed?

**Comment by kevtimova** [comment]
Hello, thank you for your interest in the project! The local contrast normalization (LCN) is a data pre-processing step which applies normalization of data features locally (in a way forcing local competition between neighboring features in a feature map) and helps with learning useful features in the decoder. You can do a control experiment in which no LCN is performed and compare the learned features in both decoders visually. You may find this article on LCN helpful: https://yeephycho.github.io/2016/08/03/normalizations_in_neural_networks/#:~:text=The%20name%20is%20%E2%80%9CLocal%20Constrast,in%20feature%20maps%20more%20significant.
